# DON'T REMOVE THIS FILE.
# This file is for render site varibles and plugins
#
# The actual configuration files are stored in the `config/_default/` folder.

######################### site variables ##############################
# customize your color and font from here.
[params.variables]
# color_primary = "#0AA8A7" # theme default
color_primary = "#46AAF3" # like microcks logo (light blue)
#color_primary = "#2096F3" # like microcks logo (strong blue)
#color_primary = "#83d0f0" # like true microcks logo (light blue)

color_secondary = "#376f92"

body_color = "#fff"
#text_color = "#777" # theme default
text_color = "#555" # all in white background, nicer by yada
text_dark = "#222"
text_light = "#959595"
border_color = "#ECECEC"
dark_body_color = "#1E262C"
dark_text_color = "#cbcbcb"
dark_text_light = "#959595"
dark_text_dark = "#fff"
dark_border_color = "#4e4e4e"
black = "#101418"
#black = "#000"
white = "#fff"
#light = "#EDF6F5" # theme default
#light = "#FFFFFF" # all in white background
light = "#F5F5F5" # nice and light grey, nicer by yada
dark = "#1b2229"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
#font_scale = "1.25" # default is "majorThird": 1.25
font_scale = "1.2"

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
# custom yada
#font_primary = "Poppins:wght@300;400;500;600;700;800"
font_primary = "Poppins:wght@500;600;700"
# theme default 
#font_primary = "Urbanist:wght@500;600;700"
font_primary_type = "sans-serif"           # [serif/sans-serif]
font_secondary = "Poppins:wght@400;500"
font_secondary_type = "sans-serif"         # [serif/sans-serif]
font_icon = "Font Awesome 6 Free"          # https://fontawesome.com/v5.15/icons/


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/regular.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/lazy-loader.js"
[[params.plugins.js]]
link = "js/tab.js"
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
# [[params.plugins.js]]
# link = "js/gallery-slider.js"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'catppuccin-mocha' # see https://xyproto.github.io/splash/docs/all.html

# table of content
[markup.tableOfContents]
startLevel = 0
endLevel = 6
ordered = false
