# This workflow adds a comment to an issue when it is labeled with 'contribution message'.
name: Add Issue Comment
#on:
  # This event will trigger the workflow run when a workflow run is requested 
  # from the 'External Link Check' workflow and the workflow run is completed. 
  # workflow_run:
  #   workflows: ["External Link Check"]
  #   types:
  #     - completed

  # This event will only trigger a workflow run if the workflow file is on the default branch.
  # ucomment the following line if you want to run the workflow manually
  # workflow_dispatch:
  # Trigger the workflow on   
  # issues:
  #   # Trigger when a new issue is opened
  #   types: [opened]
on:
  issues:
    types:
      - labeled

jobs:
  add-comment:
    # Only run this job if the issue is labeled with 'contribution message'
    # to be commented on if you want to run the workflow manually
    # if: github.event.label.name == 'contribution message'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # Step to checkout the repository this is necessary to access the contribution message file
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set issue number
        id: extract_issue_number
        run: echo "ISSUE_NUMBER=${{ github.event.workflow_run.payload.issue.number }}" >> $GITHUB_ENV
          
      - name: Add contribution message as new comment
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: gh issue comment "$NUMBER" --body-file "$BODY"
        #run: gh issue comment "${{ env.NUMBER }}" --body-file "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          # NUMBER: ${{ env.ISSUE_NUMBER }}
          BODY: "./.github/contribution_message.md"

      # # Step to add a comment to the issue with the contribution message  
      # - name: Add contribution message as new comment
      #   run: gh issue comment "$NUMBER" --body-file "$BODY"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NUMBER: ${{ github.event.issue_number }}
      #     BODY: "./.github/contribution_message.md"
