# This workflow adds a comment to an issue when it is labeled with 'contribution message'.
name: Add Issue Comment
on:
  issues:
    types:
      - created
jobs:
  add-comment:
    if: github.event.label.name == 'contribution message'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add contribution message as new comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: |
            $(< ./contribution_message.md) > BODY
